# Generated by Django 2.1.15 on 2020-02-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yukyu',
            name='busyo',
            field=models.CharField(db_column='部署', max_length=100),
        ),
        migrations.AlterField(
            model_name='yukyu',
            name='kikan_date',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='yukyu',
            name='kikan_time',
            field=models.PositiveSmallIntegerField(choices=[(1, '全日'), (2, 'AM'), (3, 'PM')]),
        ),
        migrations.AlterField(
            model_name='yukyu',
            name='kyuka_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '有給休暇'), (2, '特別休暇'), (3, '欠勤'), (4, '代休')]),
        ),
    ]
