# Generated by Django 2.1.15 on 2020-02-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200205_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yukyu',
            name='busyo',
            field=models.CharField(max_length=100, verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='yukyu',
            name='kikan_date',
            field=models.PositiveSmallIntegerField(verbose_name='期間'),
        ),
        migrations.AlterField(
            model_name='yukyu',
            name='kikan_time',
            field=models.PositiveSmallIntegerField(choices=[(1, '全日'), (2, 'AM'), (3, 'PM')], verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='yukyu',
            name='kyuka_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '有給休暇'), (2, '特別休暇'), (3, '欠勤'), (4, '代休')], verbose_name='休暇種類'),
        ),
        migrations.AlterField(
            model_name='yukyu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='yukyu',
            name='riyuu',
            field=models.TextField(verbose_name='理由'),
        ),
        migrations.AlterField(
            model_name='yukyu',
            name='start_date',
            field=models.DateField(verbose_name='取得日'),
        ),
    ]
