# Generated by Django 2.1.15 on 2020-02-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200206_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yukyu',
            name='kikan_date',
        ),
        migrations.RemoveField(
            model_name='yukyu',
            name='kikan_time',
        ),
        migrations.AddField(
            model_name='yukyu',
            name='kikan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'AM'), (2, 'PM'), (3, '1'), (4, '2'), (5, '3'), (6, '4'), (7, '5'), (8, '6')], default=1, verbose_name='時間'),
            preserve_default=False,
        ),
    ]
